/* Generated by Yosys 0.57+218 (git sha1 7ebd97216, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module nr_divider_18bit_pipelined(clk, rst_n, enable, dividend_A, divisor_D, quotient_Y, valid_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input enable;
  wire enable;
  input [17:0] dividend_A;
  wire [17:0] dividend_A;
  input [17:0] divisor_D;
  wire [17:0] divisor_D;
  output [17:0] quotient_Y;
  wire [17:0] quotient_Y;
  output valid_out;
  wire valid_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire [18:0] _166_;
  wire [18:0] _167_;
  wire [18:0] _168_;
  wire [19:0] _169_;
  wire [19:0] _170_;
  wire [18:0] _171_;
  wire [18:0] _172_;
  wire [18:0] _173_;
  wire [19:0] _174_;
  wire [19:0] _175_;
  wire [17:0] _176_;
  wire [17:0] _177_;
  wire [17:0] _178_;
  wire [19:0] _179_;
  wire [19:0] _180_;
  wire _181_;
  wire [14:0] _182_;
  wire [14:0] _183_;
  wire [14:0] _184_;
  wire [14:0] _185_;
  wire [14:0] _186_;
  wire [14:0] _187_;
  wire _188_;
  wire [17:0] _189_;
  wire [17:0] _190_;
  wire _191_;
  wire [17:0] _192_;
  wire _193_;
  wire [0:0] _194_;
  wire [32:0] final_mult;
  wire [17:0] stg1_A;
  wire [17:0] stg1_D;
  wire [32:0] stg1_D_mult;
  wire [17:0] stg1_X0;
  wire stg1_valid;
  wire [17:0] stg2_A;
  wire [17:0] stg2_D;
  wire [17:0] stg2_X1;
  wire [32:0] stg2_X1_mult;
  wire stg2_valid;
  wire [17:0] stg3_A;
  wire [17:0] stg3_X2;
  wire [35:0] stg3_X2_mult;
  wire stg3_valid;
  wire [17:0] x0_d;
  wire [35:0] x0_d_mult;
  wire [17:0] x1_d;
  wire [35:0] x1_d_mult;
  INV _195_ (
    .I(_194_),
    .O(_000_)
  );
  INV _196_ (
    .I(x1_d[0]),
    .O(_171_[0])
  );
  INV _197_ (
    .I(x1_d[1]),
    .O(_171_[1])
  );
  INV _198_ (
    .I(x1_d[2]),
    .O(_171_[2])
  );
  INV _199_ (
    .I(x1_d[3]),
    .O(_171_[3])
  );
  INV _200_ (
    .I(x1_d[4]),
    .O(_171_[4])
  );
  INV _201_ (
    .I(x1_d[5]),
    .O(_171_[5])
  );
  INV _202_ (
    .I(x1_d[6]),
    .O(_171_[6])
  );
  INV _203_ (
    .I(x1_d[7]),
    .O(_171_[7])
  );
  INV _204_ (
    .I(x1_d[8]),
    .O(_171_[8])
  );
  INV _205_ (
    .I(x1_d[9]),
    .O(_171_[9])
  );
  INV _206_ (
    .I(x1_d[10]),
    .O(_171_[10])
  );
  INV _207_ (
    .I(x1_d[11]),
    .O(_171_[11])
  );
  INV _208_ (
    .I(x1_d[12]),
    .O(_171_[12])
  );
  INV _209_ (
    .I(x1_d[13]),
    .O(_171_[13])
  );
  INV _210_ (
    .I(x1_d[14]),
    .O(_171_[14])
  );
  INV _211_ (
    .I(x1_d[15]),
    .O(_171_[15])
  );
  INV _212_ (
    .I(x1_d[17]),
    .O(_171_[18])
  );
  INV _213_ (
    .I(stg1_D_mult[15]),
    .O(_176_[0])
  );
  INV _214_ (
    .I(stg1_D_mult[16]),
    .O(_176_[1])
  );
  INV _215_ (
    .I(stg1_D_mult[17]),
    .O(_176_[2])
  );
  INV _216_ (
    .I(stg1_D_mult[19]),
    .O(_176_[4])
  );
  INV _217_ (
    .I(stg1_D_mult[22]),
    .O(_176_[7])
  );
  INV _218_ (
    .I(stg1_D_mult[24]),
    .O(_176_[9])
  );
  INV _219_ (
    .I(stg1_D_mult[25]),
    .O(_176_[10])
  );
  INV _220_ (
    .I(stg1_D_mult[27]),
    .O(_176_[12])
  );
  INV _221_ (
    .I(stg1_D_mult[30]),
    .O(_176_[15])
  );
  INV _222_ (
    .I(stg1_D_mult[32]),
    .O(_176_[17])
  );
  INV _223_ (
    .I(x0_d[0]),
    .O(_166_[0])
  );
  INV _224_ (
    .I(x0_d[1]),
    .O(_166_[1])
  );
  INV _225_ (
    .I(x0_d[2]),
    .O(_166_[2])
  );
  INV _226_ (
    .I(x0_d[3]),
    .O(_166_[3])
  );
  INV _227_ (
    .I(x0_d[4]),
    .O(_166_[4])
  );
  INV _228_ (
    .I(x0_d[5]),
    .O(_166_[5])
  );
  INV _229_ (
    .I(x0_d[6]),
    .O(_166_[6])
  );
  INV _230_ (
    .I(x0_d[7]),
    .O(_166_[7])
  );
  INV _231_ (
    .I(x0_d[8]),
    .O(_166_[8])
  );
  INV _232_ (
    .I(x0_d[9]),
    .O(_166_[9])
  );
  INV _233_ (
    .I(x0_d[10]),
    .O(_166_[10])
  );
  INV _234_ (
    .I(x0_d[11]),
    .O(_166_[11])
  );
  INV _235_ (
    .I(x0_d[12]),
    .O(_166_[12])
  );
  INV _236_ (
    .I(x0_d[13]),
    .O(_166_[13])
  );
  INV _237_ (
    .I(x0_d[14]),
    .O(_166_[14])
  );
  INV _238_ (
    .I(x0_d[15]),
    .O(_166_[15])
  );
  INV _239_ (
    .I(x0_d[17]),
    .O(_166_[18])
  );
  INV _240_ (
    .I(_194_),
    .O(_001_)
  );
  INV _241_ (
    .I(_194_),
    .O(_002_)
  );
  INV _242_ (
    .I(_194_),
    .O(_003_)
  );
  INV _243_ (
    .I(_194_),
    .O(_004_)
  );
  INV _244_ (
    .I(_194_),
    .O(_005_)
  );
  INV _245_ (
    .I(_194_),
    .O(_006_)
  );
  INV _246_ (
    .I(_194_),
    .O(_007_)
  );
  INV _247_ (
    .I(_194_),
    .O(_008_)
  );
  INV _248_ (
    .I(_194_),
    .O(_009_)
  );
  INV _249_ (
    .I(_194_),
    .O(_010_)
  );
  INV _250_ (
    .I(_194_),
    .O(_011_)
  );
  INV _251_ (
    .I(_194_),
    .O(_012_)
  );
  INV _252_ (
    .I(_194_),
    .O(_013_)
  );
  INV _253_ (
    .I(_194_),
    .O(_014_)
  );
  INV _254_ (
    .I(_194_),
    .O(_015_)
  );
  INV _255_ (
    .I(_194_),
    .O(_016_)
  );
  INV _256_ (
    .I(_194_),
    .O(_017_)
  );
  INV _257_ (
    .I(_194_),
    .O(_018_)
  );
  INV _258_ (
    .I(_194_),
    .O(_019_)
  );
  INV _259_ (
    .I(_194_),
    .O(_020_)
  );
  INV _260_ (
    .I(_194_),
    .O(_021_)
  );
  INV _261_ (
    .I(_194_),
    .O(_022_)
  );
  INV _262_ (
    .I(_194_),
    .O(_023_)
  );
  INV _263_ (
    .I(_194_),
    .O(_024_)
  );
  INV _264_ (
    .I(_194_),
    .O(_025_)
  );
  INV _265_ (
    .I(_194_),
    .O(_026_)
  );
  INV _266_ (
    .I(_194_),
    .O(_027_)
  );
  INV _267_ (
    .I(_194_),
    .O(_028_)
  );
  INV _268_ (
    .I(_194_),
    .O(_029_)
  );
  INV _269_ (
    .I(_194_),
    .O(_030_)
  );
  INV _270_ (
    .I(_194_),
    .O(_031_)
  );
  INV _271_ (
    .I(_194_),
    .O(_032_)
  );
  INV _272_ (
    .I(_194_),
    .O(_033_)
  );
  INV _273_ (
    .I(_194_),
    .O(_034_)
  );
  INV _274_ (
    .I(_194_),
    .O(_035_)
  );
  INV _275_ (
    .I(_194_),
    .O(_036_)
  );
  INV _276_ (
    .I(_194_),
    .O(_037_)
  );
  INV _277_ (
    .I(_194_),
    .O(_038_)
  );
  INV _278_ (
    .I(_194_),
    .O(_039_)
  );
  INV _279_ (
    .I(_194_),
    .O(_040_)
  );
  INV _280_ (
    .I(_194_),
    .O(_041_)
  );
  INV _281_ (
    .I(_194_),
    .O(_042_)
  );
  INV _282_ (
    .I(_194_),
    .O(_043_)
  );
  INV _283_ (
    .I(_194_),
    .O(_044_)
  );
  INV _284_ (
    .I(_194_),
    .O(_045_)
  );
  INV _285_ (
    .I(_194_),
    .O(_046_)
  );
  INV _286_ (
    .I(_194_),
    .O(_047_)
  );
  INV _287_ (
    .I(_194_),
    .O(_048_)
  );
  INV _288_ (
    .I(_194_),
    .O(_049_)
  );
  INV _289_ (
    .I(_194_),
    .O(_050_)
  );
  INV _290_ (
    .I(_194_),
    .O(_051_)
  );
  INV _291_ (
    .I(_194_),
    .O(_052_)
  );
  INV _292_ (
    .I(_194_),
    .O(_053_)
  );
  INV _293_ (
    .I(_194_),
    .O(_054_)
  );
  INV _294_ (
    .I(_194_),
    .O(_055_)
  );
  INV _295_ (
    .I(_194_),
    .O(_056_)
  );
  INV _296_ (
    .I(_194_),
    .O(_057_)
  );
  INV _297_ (
    .I(_194_),
    .O(_058_)
  );
  INV _298_ (
    .I(_194_),
    .O(_059_)
  );
  INV _299_ (
    .I(_194_),
    .O(_060_)
  );
  INV _300_ (
    .I(_194_),
    .O(_061_)
  );
  INV _301_ (
    .I(_194_),
    .O(_062_)
  );
  INV _302_ (
    .I(_194_),
    .O(_063_)
  );
  INV _303_ (
    .I(_194_),
    .O(_064_)
  );
  INV _304_ (
    .I(_194_),
    .O(_065_)
  );
  INV _305_ (
    .I(_194_),
    .O(_066_)
  );
  INV _306_ (
    .I(_194_),
    .O(_067_)
  );
  INV _307_ (
    .I(_194_),
    .O(_068_)
  );
  INV _308_ (
    .I(_194_),
    .O(_069_)
  );
  INV _309_ (
    .I(_194_),
    .O(_070_)
  );
  INV _310_ (
    .I(_194_),
    .O(_071_)
  );
  INV _311_ (
    .I(_194_),
    .O(_072_)
  );
  INV _312_ (
    .I(_194_),
    .O(_073_)
  );
  INV _313_ (
    .I(_194_),
    .O(_074_)
  );
  INV _314_ (
    .I(_194_),
    .O(_075_)
  );
  INV _315_ (
    .I(_194_),
    .O(_076_)
  );
  INV _316_ (
    .I(_194_),
    .O(_077_)
  );
  INV _317_ (
    .I(_194_),
    .O(_078_)
  );
  INV _318_ (
    .I(_194_),
    .O(_079_)
  );
  INV _319_ (
    .I(_194_),
    .O(_080_)
  );
  INV _320_ (
    .I(_194_),
    .O(_081_)
  );
  INV _321_ (
    .I(_194_),
    .O(_082_)
  );
  INV _322_ (
    .I(_194_),
    .O(_083_)
  );
  INV _323_ (
    .I(_194_),
    .O(_084_)
  );
  INV _324_ (
    .I(_194_),
    .O(_085_)
  );
  INV _325_ (
    .I(_194_),
    .O(_086_)
  );
  INV _326_ (
    .I(_194_),
    .O(_087_)
  );
  INV _327_ (
    .I(_194_),
    .O(_088_)
  );
  INV _328_ (
    .I(_194_),
    .O(_089_)
  );
  INV _329_ (
    .I(_194_),
    .O(_090_)
  );
  INV _330_ (
    .I(_194_),
    .O(_091_)
  );
  INV _331_ (
    .I(_194_),
    .O(_092_)
  );
  INV _332_ (
    .I(_194_),
    .O(_093_)
  );
  INV _333_ (
    .I(_194_),
    .O(_094_)
  );
  INV _334_ (
    .I(_194_),
    .O(_095_)
  );
  INV _335_ (
    .I(_194_),
    .O(_096_)
  );
  INV _336_ (
    .I(_194_),
    .O(_097_)
  );
  INV _337_ (
    .I(_194_),
    .O(_098_)
  );
  INV _338_ (
    .I(_194_),
    .O(_099_)
  );
  INV _339_ (
    .I(_194_),
    .O(_100_)
  );
  INV _340_ (
    .I(_194_),
    .O(_101_)
  );
  INV _341_ (
    .I(_194_),
    .O(_102_)
  );
  INV _342_ (
    .I(_194_),
    .O(_103_)
  );
  INV _343_ (
    .I(_194_),
    .O(_104_)
  );
  INV _344_ (
    .I(_194_),
    .O(_105_)
  );
  INV _345_ (
    .I(_194_),
    .O(_106_)
  );
  INV _346_ (
    .I(_194_),
    .O(_107_)
  );
  INV _347_ (
    .I(_194_),
    .O(_108_)
  );
  INV _348_ (
    .I(_194_),
    .O(_109_)
  );
  INV _349_ (
    .I(_194_),
    .O(_110_)
  );
  INV _350_ (
    .I(_194_),
    .O(_111_)
  );
  INV _351_ (
    .I(_194_),
    .O(_112_)
  );
  INV _352_ (
    .I(_194_),
    .O(_113_)
  );
  INV _353_ (
    .I(_194_),
    .O(_114_)
  );
  INV _354_ (
    .I(_194_),
    .O(_115_)
  );
  INV _355_ (
    .I(_194_),
    .O(_116_)
  );
  INV _356_ (
    .I(_194_),
    .O(_117_)
  );
  INV _357_ (
    .I(_194_),
    .O(_118_)
  );
  INV _358_ (
    .I(_194_),
    .O(_119_)
  );
  INV _359_ (
    .I(_194_),
    .O(_120_)
  );
  INV _360_ (
    .I(_194_),
    .O(_121_)
  );
  INV _361_ (
    .I(_194_),
    .O(_122_)
  );
  INV _362_ (
    .I(_194_),
    .O(_123_)
  );
  INV _363_ (
    .I(_194_),
    .O(_124_)
  );
  INV _364_ (
    .I(_194_),
    .O(_125_)
  );
  INV _365_ (
    .I(_194_),
    .O(_126_)
  );
  INV _366_ (
    .I(_194_),
    .O(_127_)
  );
  INV _367_ (
    .I(_194_),
    .O(_128_)
  );
  INV _368_ (
    .I(_194_),
    .O(_129_)
  );
  INV _369_ (
    .I(_194_),
    .O(_130_)
  );
  INV _370_ (
    .I(_194_),
    .O(_131_)
  );
  INV _371_ (
    .I(_194_),
    .O(_132_)
  );
  INV _372_ (
    .I(_194_),
    .O(_133_)
  );
  INV _373_ (
    .I(_194_),
    .O(_134_)
  );
  INV _374_ (
    .I(_194_),
    .O(_135_)
  );
  INV _375_ (
    .I(_194_),
    .O(_136_)
  );
  INV _376_ (
    .I(_194_),
    .O(_137_)
  );
  INV _377_ (
    .I(_194_),
    .O(_138_)
  );
  INV _378_ (
    .I(_194_),
    .O(_139_)
  );
  INV _379_ (
    .I(_194_),
    .O(_140_)
  );
  INV _380_ (
    .I(_194_),
    .O(_141_)
  );
  INV _381_ (
    .I(_194_),
    .O(_142_)
  );
  INV _382_ (
    .I(_194_),
    .O(_143_)
  );
  INV _383_ (
    .I(_194_),
    .O(_144_)
  );
  INV _384_ (
    .I(_194_),
    .O(_145_)
  );
  INV _385_ (
    .I(_194_),
    .O(_146_)
  );
  INV _386_ (
    .I(_194_),
    .O(_147_)
  );
  INV _387_ (
    .I(_194_),
    .O(_148_)
  );
  INV _388_ (
    .I(_194_),
    .O(_149_)
  );
  INV _389_ (
    .I(_194_),
    .O(_150_)
  );
  INV _390_ (
    .I(_194_),
    .O(_151_)
  );
  INV _391_ (
    .I(_194_),
    .O(_152_)
  );
  INV _392_ (
    .I(_194_),
    .O(_153_)
  );
  INV _393_ (
    .I(_194_),
    .O(_154_)
  );
  INV _394_ (
    .I(_194_),
    .O(_155_)
  );
  INV _395_ (
    .I(_194_),
    .O(_156_)
  );
  INV _396_ (
    .I(_194_),
    .O(_157_)
  );
  INV _397_ (
    .I(_194_),
    .O(_158_)
  );
  INV _398_ (
    .I(_194_),
    .O(_159_)
  );
  INV _399_ (
    .I(_194_),
    .O(_160_)
  );
  INV _400_ (
    .I(_194_),
    .O(_161_)
  );
  INV _401_ (
    .I(_194_),
    .O(_162_)
  );
  INV _402_ (
    .I(_194_),
    .O(_163_)
  );
  INV _403_ (
    .I(_194_),
    .O(_164_)
  );
  INV _404_ (
    .I(_194_),
    .O(_165_)
  );
  CARRY4 _405_ (
    .CI(1'h0),
    .CO(_167_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h0),
    .O(_168_[3:0]),
    .S(_166_[3:0])
  );
  CARRY4 _406_ (
    .CI(_167_[3]),
    .CO(_167_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_168_[7:4]),
    .S(_166_[7:4])
  );
  CARRY4 _407_ (
    .CI(_167_[7]),
    .CO(_167_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_168_[11:8]),
    .S(_166_[11:8])
  );
  CARRY4 _408_ (
    .CI(_167_[11]),
    .CO(_167_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_168_[15:12]),
    .S(_166_[15:12])
  );
  CARRY4 _409_ (
    .CI(_167_[15]),
    .CO({ _169_[19], _167_[18:16] }),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O({ _170_[19], _168_[18:16] }),
    .S({ 1'h0, _166_[18], _166_[18], x0_d[16] })
  );
  CARRY4 _410_ (
    .CI(1'h0),
    .CO(_172_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h0),
    .O(_173_[3:0]),
    .S(_171_[3:0])
  );
  CARRY4 _411_ (
    .CI(_172_[3]),
    .CO(_172_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_173_[7:4]),
    .S(_171_[7:4])
  );
  CARRY4 _412_ (
    .CI(_172_[7]),
    .CO(_172_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_173_[11:8]),
    .S(_171_[11:8])
  );
  CARRY4 _413_ (
    .CI(_172_[11]),
    .CO(_172_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_173_[15:12]),
    .S(_171_[15:12])
  );
  CARRY4 _414_ (
    .CI(_172_[15]),
    .CO({ _174_[19], _172_[18:16] }),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O({ _175_[19], _173_[18:16] }),
    .S({ 1'h0, _171_[18], _171_[18], x1_d[16] })
  );
  CARRY4 _415_ (
    .CI(1'h0),
    .CO(_177_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h8),
    .O(_178_[3:0]),
    .S({ stg1_D_mult[18], _176_[2:0] })
  );
  CARRY4 _416_ (
    .CI(_177_[3]),
    .CO(_177_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h6),
    .O(_178_[7:4]),
    .S({ _176_[7], stg1_D_mult[21:20], _176_[4] })
  );
  CARRY4 _417_ (
    .CI(_177_[7]),
    .CO(_177_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h9),
    .O(_178_[11:8]),
    .S({ stg1_D_mult[26], _176_[10:9], stg1_D_mult[23] })
  );
  CARRY4 _418_ (
    .CI(_177_[11]),
    .CO(_177_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h6),
    .O(_178_[15:12]),
    .S({ _176_[15], stg1_D_mult[29:28], _176_[12] })
  );
  CARRY4 _419_ (
    .CI(_177_[15]),
    .CO({ _179_[19:18], _177_[17:16] }),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O({ _180_[19:18], _178_[17:16] }),
    .S({ 2'h0, _176_[17], stg1_D_mult[31] })
  );
  BUFG _420_ (
    .I(_181_),
    .O(_188_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _421_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_000_),
    .D(stg1_D[0]),
    .Q(stg2_D[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _422_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_001_),
    .D(stg1_D[1]),
    .Q(stg2_D[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _423_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_002_),
    .D(stg1_D[2]),
    .Q(stg2_D[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _424_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_003_),
    .D(stg1_D[3]),
    .Q(stg2_D[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _425_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_004_),
    .D(stg1_D[4]),
    .Q(stg2_D[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _426_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_005_),
    .D(stg1_D[5]),
    .Q(stg2_D[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _427_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_006_),
    .D(stg1_D[6]),
    .Q(stg2_D[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _428_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_007_),
    .D(stg1_D[7]),
    .Q(stg2_D[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _429_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_008_),
    .D(stg1_D[8]),
    .Q(stg2_D[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _430_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_009_),
    .D(stg1_D[9]),
    .Q(stg2_D[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _431_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_010_),
    .D(stg1_D[10]),
    .Q(stg2_D[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _432_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_011_),
    .D(stg1_D[11]),
    .Q(stg2_D[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _433_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_012_),
    .D(stg1_D[12]),
    .Q(stg2_D[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _434_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_013_),
    .D(stg1_D[13]),
    .Q(stg2_D[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _435_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_014_),
    .D(stg1_D[14]),
    .Q(stg2_D[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _436_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_015_),
    .D(stg1_D[15]),
    .Q(stg2_D[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _437_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_016_),
    .D(stg1_D[16]),
    .Q(stg2_D[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _438_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_017_),
    .D(stg1_D[17]),
    .Q(stg2_D[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _439_ (
    .C(_188_),
    .CE(1'h1),
    .CLR(_018_),
    .D(stg3_valid),
    .Q(_193_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _440_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_019_),
    .D(stg3_X2_mult[15]),
    .Q(stg3_X2[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _441_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_020_),
    .D(stg3_X2_mult[16]),
    .Q(stg3_X2[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _442_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_021_),
    .D(stg3_X2_mult[17]),
    .Q(stg3_X2[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _443_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_022_),
    .D(stg3_X2_mult[18]),
    .Q(stg3_X2[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _444_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_023_),
    .D(stg3_X2_mult[19]),
    .Q(stg3_X2[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _445_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_024_),
    .D(stg3_X2_mult[20]),
    .Q(stg3_X2[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _446_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_025_),
    .D(stg3_X2_mult[21]),
    .Q(stg3_X2[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _447_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_026_),
    .D(stg3_X2_mult[22]),
    .Q(stg3_X2[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _448_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_027_),
    .D(stg3_X2_mult[23]),
    .Q(stg3_X2[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _449_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_028_),
    .D(stg3_X2_mult[24]),
    .Q(stg3_X2[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _450_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_029_),
    .D(stg3_X2_mult[25]),
    .Q(stg3_X2[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _451_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_030_),
    .D(stg3_X2_mult[26]),
    .Q(stg3_X2[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _452_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_031_),
    .D(stg3_X2_mult[27]),
    .Q(stg3_X2[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _453_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_032_),
    .D(stg3_X2_mult[28]),
    .Q(stg3_X2[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _454_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_033_),
    .D(stg3_X2_mult[29]),
    .Q(stg3_X2[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _455_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_034_),
    .D(stg3_X2_mult[30]),
    .Q(stg3_X2[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _456_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_035_),
    .D(stg3_X2_mult[31]),
    .Q(stg3_X2[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _457_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_036_),
    .D(stg3_X2_mult[32]),
    .Q(stg3_X2[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _458_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_037_),
    .D(stg2_A[0]),
    .Q(stg3_A[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _459_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_038_),
    .D(stg2_A[1]),
    .Q(stg3_A[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _460_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_039_),
    .D(stg2_A[2]),
    .Q(stg3_A[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _461_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_040_),
    .D(stg2_A[3]),
    .Q(stg3_A[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _462_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_041_),
    .D(stg2_A[4]),
    .Q(stg3_A[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _463_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_042_),
    .D(stg2_A[5]),
    .Q(stg3_A[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _464_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_043_),
    .D(stg2_A[6]),
    .Q(stg3_A[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _465_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_044_),
    .D(stg2_A[7]),
    .Q(stg3_A[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _466_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_045_),
    .D(stg2_A[8]),
    .Q(stg3_A[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _467_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_046_),
    .D(stg2_A[9]),
    .Q(stg3_A[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _468_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_047_),
    .D(stg2_A[10]),
    .Q(stg3_A[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _469_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_048_),
    .D(stg2_A[11]),
    .Q(stg3_A[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _470_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_049_),
    .D(stg2_A[12]),
    .Q(stg3_A[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _471_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_050_),
    .D(stg2_A[13]),
    .Q(stg3_A[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _472_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_051_),
    .D(stg2_A[14]),
    .Q(stg3_A[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _473_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_052_),
    .D(stg2_A[15]),
    .Q(stg3_A[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _474_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_053_),
    .D(stg2_A[16]),
    .Q(stg3_A[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _475_ (
    .C(_188_),
    .CE(stg2_valid),
    .CLR(_054_),
    .D(stg2_A[17]),
    .Q(stg3_A[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _476_ (
    .C(_188_),
    .CE(1'h1),
    .CLR(_055_),
    .D(_191_),
    .Q(stg1_valid)
  );
  FDCE #(
    .INIT(1'hx)
  ) _477_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_056_),
    .D(_189_[0]),
    .Q(stg1_A[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _478_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_057_),
    .D(_189_[1]),
    .Q(stg1_A[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _479_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_058_),
    .D(_189_[2]),
    .Q(stg1_A[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _480_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_059_),
    .D(_189_[3]),
    .Q(stg1_A[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _481_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_060_),
    .D(_189_[4]),
    .Q(stg1_A[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _482_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_061_),
    .D(_189_[5]),
    .Q(stg1_A[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _483_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_062_),
    .D(_189_[6]),
    .Q(stg1_A[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _484_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_063_),
    .D(_189_[7]),
    .Q(stg1_A[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _485_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_064_),
    .D(_189_[8]),
    .Q(stg1_A[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _486_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_065_),
    .D(_189_[9]),
    .Q(stg1_A[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _487_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_066_),
    .D(_189_[10]),
    .Q(stg1_A[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _488_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_067_),
    .D(_189_[11]),
    .Q(stg1_A[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _489_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_068_),
    .D(_189_[12]),
    .Q(stg1_A[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _490_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_069_),
    .D(_189_[13]),
    .Q(stg1_A[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _491_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_070_),
    .D(_189_[14]),
    .Q(stg1_A[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _492_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_071_),
    .D(_189_[15]),
    .Q(stg1_A[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _493_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_072_),
    .D(_189_[16]),
    .Q(stg1_A[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _494_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_073_),
    .D(_189_[17]),
    .Q(stg1_A[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _495_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_074_),
    .D(_178_[0]),
    .Q(stg1_X0[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _496_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_075_),
    .D(_178_[1]),
    .Q(stg1_X0[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _497_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_076_),
    .D(_178_[2]),
    .Q(stg1_X0[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _498_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_077_),
    .D(_178_[3]),
    .Q(stg1_X0[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _499_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_078_),
    .D(_178_[4]),
    .Q(stg1_X0[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _500_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_079_),
    .D(_178_[5]),
    .Q(stg1_X0[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _501_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_080_),
    .D(_178_[6]),
    .Q(stg1_X0[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _502_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_081_),
    .D(_178_[7]),
    .Q(stg1_X0[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _503_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_082_),
    .D(_178_[8]),
    .Q(stg1_X0[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _504_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_083_),
    .D(_178_[9]),
    .Q(stg1_X0[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _505_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_084_),
    .D(_178_[10]),
    .Q(stg1_X0[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _506_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_085_),
    .D(_178_[11]),
    .Q(stg1_X0[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _507_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_086_),
    .D(_178_[12]),
    .Q(stg1_X0[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _508_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_087_),
    .D(_178_[13]),
    .Q(stg1_X0[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _509_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_088_),
    .D(_178_[14]),
    .Q(stg1_X0[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _510_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_089_),
    .D(_178_[15]),
    .Q(stg1_X0[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _511_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_090_),
    .D(_178_[16]),
    .Q(stg1_X0[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _512_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_091_),
    .D(_178_[17]),
    .Q(stg1_X0[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _513_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_092_),
    .D(_190_[0]),
    .Q(stg1_D[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _514_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_093_),
    .D(_190_[1]),
    .Q(stg1_D[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _515_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_094_),
    .D(_190_[2]),
    .Q(stg1_D[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _516_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_095_),
    .D(_190_[3]),
    .Q(stg1_D[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _517_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_096_),
    .D(_190_[4]),
    .Q(stg1_D[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _518_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_097_),
    .D(_190_[5]),
    .Q(stg1_D[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _519_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_098_),
    .D(_190_[6]),
    .Q(stg1_D[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _520_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_099_),
    .D(_190_[7]),
    .Q(stg1_D[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _521_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_100_),
    .D(_190_[8]),
    .Q(stg1_D[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _522_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_101_),
    .D(_190_[9]),
    .Q(stg1_D[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _523_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_102_),
    .D(_190_[10]),
    .Q(stg1_D[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _524_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_103_),
    .D(_190_[11]),
    .Q(stg1_D[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _525_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_104_),
    .D(_190_[12]),
    .Q(stg1_D[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _526_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_105_),
    .D(_190_[13]),
    .Q(stg1_D[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _527_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_106_),
    .D(_190_[14]),
    .Q(stg1_D[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _528_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_107_),
    .D(_190_[15]),
    .Q(stg1_D[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _529_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_108_),
    .D(_190_[16]),
    .Q(stg1_D[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _530_ (
    .C(_188_),
    .CE(_191_),
    .CLR(_109_),
    .D(_190_[17]),
    .Q(stg1_D[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _531_ (
    .C(_188_),
    .CE(1'h1),
    .CLR(_110_),
    .D(stg1_valid),
    .Q(stg2_valid)
  );
  FDCE #(
    .INIT(1'hx)
  ) _532_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_111_),
    .D(final_mult[15]),
    .Q(_192_[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _533_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_112_),
    .D(final_mult[16]),
    .Q(_192_[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _534_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_113_),
    .D(final_mult[17]),
    .Q(_192_[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _535_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_114_),
    .D(final_mult[18]),
    .Q(_192_[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _536_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_115_),
    .D(final_mult[19]),
    .Q(_192_[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _537_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_116_),
    .D(final_mult[20]),
    .Q(_192_[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _538_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_117_),
    .D(final_mult[21]),
    .Q(_192_[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _539_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_118_),
    .D(final_mult[22]),
    .Q(_192_[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _540_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_119_),
    .D(final_mult[23]),
    .Q(_192_[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _541_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_120_),
    .D(final_mult[24]),
    .Q(_192_[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _542_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_121_),
    .D(final_mult[25]),
    .Q(_192_[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _543_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_122_),
    .D(final_mult[26]),
    .Q(_192_[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _544_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_123_),
    .D(final_mult[27]),
    .Q(_192_[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _545_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_124_),
    .D(final_mult[28]),
    .Q(_192_[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _546_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_125_),
    .D(final_mult[29]),
    .Q(_192_[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _547_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_126_),
    .D(final_mult[30]),
    .Q(_192_[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _548_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_127_),
    .D(final_mult[31]),
    .Q(_192_[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _549_ (
    .C(_188_),
    .CE(stg3_valid),
    .CLR(_128_),
    .D(final_mult[32]),
    .Q(_192_[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _550_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_129_),
    .D(stg2_X1_mult[15]),
    .Q(stg2_X1[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _551_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_130_),
    .D(stg2_X1_mult[16]),
    .Q(stg2_X1[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _552_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_131_),
    .D(stg2_X1_mult[17]),
    .Q(stg2_X1[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _553_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_132_),
    .D(stg2_X1_mult[18]),
    .Q(stg2_X1[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _554_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_133_),
    .D(stg2_X1_mult[19]),
    .Q(stg2_X1[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _555_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_134_),
    .D(stg2_X1_mult[20]),
    .Q(stg2_X1[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _556_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_135_),
    .D(stg2_X1_mult[21]),
    .Q(stg2_X1[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _557_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_136_),
    .D(stg2_X1_mult[22]),
    .Q(stg2_X1[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _558_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_137_),
    .D(stg2_X1_mult[23]),
    .Q(stg2_X1[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _559_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_138_),
    .D(stg2_X1_mult[24]),
    .Q(stg2_X1[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _560_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_139_),
    .D(stg2_X1_mult[25]),
    .Q(stg2_X1[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _561_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_140_),
    .D(stg2_X1_mult[26]),
    .Q(stg2_X1[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _562_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_141_),
    .D(stg2_X1_mult[27]),
    .Q(stg2_X1[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _563_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_142_),
    .D(stg2_X1_mult[28]),
    .Q(stg2_X1[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _564_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_143_),
    .D(stg2_X1_mult[29]),
    .Q(stg2_X1[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _565_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_144_),
    .D(stg2_X1_mult[30]),
    .Q(stg2_X1[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _566_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_145_),
    .D(stg2_X1_mult[31]),
    .Q(stg2_X1[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _567_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_146_),
    .D(stg2_X1_mult[32]),
    .Q(stg2_X1[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _568_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_147_),
    .D(stg1_A[0]),
    .Q(stg2_A[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _569_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_148_),
    .D(stg1_A[1]),
    .Q(stg2_A[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _570_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_149_),
    .D(stg1_A[2]),
    .Q(stg2_A[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _571_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_150_),
    .D(stg1_A[3]),
    .Q(stg2_A[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _572_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_151_),
    .D(stg1_A[4]),
    .Q(stg2_A[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _573_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_152_),
    .D(stg1_A[5]),
    .Q(stg2_A[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _574_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_153_),
    .D(stg1_A[6]),
    .Q(stg2_A[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _575_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_154_),
    .D(stg1_A[7]),
    .Q(stg2_A[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _576_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_155_),
    .D(stg1_A[8]),
    .Q(stg2_A[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _577_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_156_),
    .D(stg1_A[9]),
    .Q(stg2_A[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _578_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_157_),
    .D(stg1_A[10]),
    .Q(stg2_A[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _579_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_158_),
    .D(stg1_A[11]),
    .Q(stg2_A[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _580_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_159_),
    .D(stg1_A[12]),
    .Q(stg2_A[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _581_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_160_),
    .D(stg1_A[13]),
    .Q(stg2_A[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _582_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_161_),
    .D(stg1_A[14]),
    .Q(stg2_A[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _583_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_162_),
    .D(stg1_A[15]),
    .Q(stg2_A[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _584_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_163_),
    .D(stg1_A[16]),
    .Q(stg2_A[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _585_ (
    .C(_188_),
    .CE(stg1_valid),
    .CLR(_164_),
    .D(stg1_A[17]),
    .Q(stg2_A[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _586_ (
    .C(_188_),
    .CE(1'h1),
    .CLR(_165_),
    .D(stg2_valid),
    .Q(stg3_valid)
  );
  IBUF _587_ (
    .I(clk),
    .O(_181_)
  );
  IBUF _588_ (
    .I(dividend_A[0]),
    .O(_189_[0])
  );
  IBUF _589_ (
    .I(dividend_A[1]),
    .O(_189_[1])
  );
  IBUF _590_ (
    .I(dividend_A[10]),
    .O(_189_[10])
  );
  IBUF _591_ (
    .I(dividend_A[11]),
    .O(_189_[11])
  );
  IBUF _592_ (
    .I(dividend_A[12]),
    .O(_189_[12])
  );
  IBUF _593_ (
    .I(dividend_A[13]),
    .O(_189_[13])
  );
  IBUF _594_ (
    .I(dividend_A[14]),
    .O(_189_[14])
  );
  IBUF _595_ (
    .I(dividend_A[15]),
    .O(_189_[15])
  );
  IBUF _596_ (
    .I(dividend_A[16]),
    .O(_189_[16])
  );
  IBUF _597_ (
    .I(dividend_A[17]),
    .O(_189_[17])
  );
  IBUF _598_ (
    .I(dividend_A[2]),
    .O(_189_[2])
  );
  IBUF _599_ (
    .I(dividend_A[3]),
    .O(_189_[3])
  );
  IBUF _600_ (
    .I(dividend_A[4]),
    .O(_189_[4])
  );
  IBUF _601_ (
    .I(dividend_A[5]),
    .O(_189_[5])
  );
  IBUF _602_ (
    .I(dividend_A[6]),
    .O(_189_[6])
  );
  IBUF _603_ (
    .I(dividend_A[7]),
    .O(_189_[7])
  );
  IBUF _604_ (
    .I(dividend_A[8]),
    .O(_189_[8])
  );
  IBUF _605_ (
    .I(dividend_A[9]),
    .O(_189_[9])
  );
  IBUF _606_ (
    .I(divisor_D[0]),
    .O(_190_[0])
  );
  IBUF _607_ (
    .I(divisor_D[1]),
    .O(_190_[1])
  );
  IBUF _608_ (
    .I(divisor_D[10]),
    .O(_190_[10])
  );
  IBUF _609_ (
    .I(divisor_D[11]),
    .O(_190_[11])
  );
  IBUF _610_ (
    .I(divisor_D[12]),
    .O(_190_[12])
  );
  IBUF _611_ (
    .I(divisor_D[13]),
    .O(_190_[13])
  );
  IBUF _612_ (
    .I(divisor_D[14]),
    .O(_190_[14])
  );
  IBUF _613_ (
    .I(divisor_D[15]),
    .O(_190_[15])
  );
  IBUF _614_ (
    .I(divisor_D[16]),
    .O(_190_[16])
  );
  IBUF _615_ (
    .I(divisor_D[17]),
    .O(_190_[17])
  );
  IBUF _616_ (
    .I(divisor_D[2]),
    .O(_190_[2])
  );
  IBUF _617_ (
    .I(divisor_D[3]),
    .O(_190_[3])
  );
  IBUF _618_ (
    .I(divisor_D[4]),
    .O(_190_[4])
  );
  IBUF _619_ (
    .I(divisor_D[5]),
    .O(_190_[5])
  );
  IBUF _620_ (
    .I(divisor_D[6]),
    .O(_190_[6])
  );
  IBUF _621_ (
    .I(divisor_D[7]),
    .O(_190_[7])
  );
  IBUF _622_ (
    .I(divisor_D[8]),
    .O(_190_[8])
  );
  IBUF _623_ (
    .I(divisor_D[9]),
    .O(_190_[9])
  );
  IBUF _624_ (
    .I(enable),
    .O(_191_)
  );
  OBUF _625_ (
    .I(_192_[0]),
    .O(quotient_Y[0])
  );
  OBUF _626_ (
    .I(_192_[1]),
    .O(quotient_Y[1])
  );
  OBUF _627_ (
    .I(_192_[10]),
    .O(quotient_Y[10])
  );
  OBUF _628_ (
    .I(_192_[11]),
    .O(quotient_Y[11])
  );
  OBUF _629_ (
    .I(_192_[12]),
    .O(quotient_Y[12])
  );
  OBUF _630_ (
    .I(_192_[13]),
    .O(quotient_Y[13])
  );
  OBUF _631_ (
    .I(_192_[14]),
    .O(quotient_Y[14])
  );
  OBUF _632_ (
    .I(_192_[15]),
    .O(quotient_Y[15])
  );
  OBUF _633_ (
    .I(_192_[16]),
    .O(quotient_Y[16])
  );
  OBUF _634_ (
    .I(_192_[17]),
    .O(quotient_Y[17])
  );
  OBUF _635_ (
    .I(_192_[2]),
    .O(quotient_Y[2])
  );
  OBUF _636_ (
    .I(_192_[3]),
    .O(quotient_Y[3])
  );
  OBUF _637_ (
    .I(_192_[4]),
    .O(quotient_Y[4])
  );
  OBUF _638_ (
    .I(_192_[5]),
    .O(quotient_Y[5])
  );
  OBUF _639_ (
    .I(_192_[6]),
    .O(quotient_Y[6])
  );
  OBUF _640_ (
    .I(_192_[7]),
    .O(quotient_Y[7])
  );
  OBUF _641_ (
    .I(_192_[8]),
    .O(quotient_Y[8])
  );
  OBUF _642_ (
    .I(_192_[9]),
    .O(quotient_Y[9])
  );
  IBUF _643_ (
    .I(rst_n),
    .O(_194_)
  );
  OBUF _644_ (
    .I(_193_),
    .O(valid_out)
  );
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _645_ (
    .A({ _190_[17], _190_[17], _190_[17], _190_[17], _190_[17], _190_[17], _190_[17], _190_[17], _190_[17], _190_[17], _190_[17], _190_[17], _190_ }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B(18'h0f0f1),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h05),
    .P({ _184_, stg1_D_mult }),
    .PCIN(48'h000000000000)
  );
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _646_ (
    .A({ stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0[17], stg1_X0 }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B(stg1_D),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h05),
    .P({ _185_, x0_d, x0_d_mult[14:0] }),
    .PCIN(48'h000000000000)
  );
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _647_ (
    .A({ _168_[18], _168_[18], _168_[18], _168_[18], _168_[18], _168_[18], _168_[18], _168_[18], _168_[18], _168_[18], _168_[18], _168_ }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B(stg1_X0),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h05),
    .P({ _183_, stg2_X1_mult }),
    .PCIN(48'h000000000000)
  );
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _648_ (
    .A({ stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1[17], stg2_X1 }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B(stg2_D),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h05),
    .P({ _187_, x1_d, x1_d_mult[14:0] }),
    .PCIN(48'h000000000000)
  );
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _649_ (
    .A({ _173_[18], _173_[18], _173_[18], _173_[18], _173_[18], _173_[18], _173_[18], _173_[18], _173_[18], _173_[18], _173_[18], _173_ }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B(stg2_X1),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h05),
    .P({ _182_, stg3_X2_mult[32:0] }),
    .PCIN(48'h000000000000)
  );
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _650_ (
    .A({ stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A[17], stg3_A }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B(stg3_X2),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h05),
    .P({ _186_, final_mult }),
    .PCIN(48'h000000000000)
  );
  assign _166_[17] = _166_[18];
  assign _169_[18:0] = _167_;
  assign _170_[18:0] = _168_;
  assign _171_[17] = _171_[18];
  assign _174_[18:0] = _172_;
  assign _175_[18:0] = _173_;
  assign _179_[17:0] = _177_;
  assign _180_[17:0] = _178_;
  assign stg3_X2_mult[35:33] = 3'hx;
  assign x0_d_mult[35:15] = { 3'hx, x0_d };
  assign x1_d_mult[35:15] = { 3'hx, x1_d };
endmodule
